version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_ctc
    environment:
      POSTGRES_USER: ctc
      POSTGRES_PASSWORD: ctc
      POSTGRES_DB: ctc_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: