[project]
name = "ctc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "neo4j-graphrag>=1.10.1",
    "openai>=2.3.0",
    "pandas>=2.3.3",
    "qdrant-client>=1.16.2",
    "requests>=2.32.5",
]
